version: 2.1

# ------------------------------
# Parameters
# ------------------------------

parameters:
  cache-version:
    type: string
    default: v6

# ------------------------------
# Executor
# ------------------------------

executors:
  node:
    working_directory: ~/repo
    docker:
    - image: circleci/node:12.16

# ------------------------------
# Commands
# ------------------------------

commands:
  checkout-and-restore-cache:
    steps:
    - checkout
    - restore_cache:
        key: &cache-key << pipeline.parameters.cache-version >>-node12-dependencies-{{ arch }}-{{ checksum "./yarn.lock" }}

  set-git-write-access:
    steps:
    - run:
        name: Setup git origin with write access
        command: git remote set-url origin "https://$GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

# ------------------------------
# Jobs
# ------------------------------

jobs:
  dependencies:
    executor: node
    steps:
    - checkout-and-restore-cache
    - run:
        name: Install dependencies
        command: yarn --prefer-offline --pure-lockfile --ignore-engines
    - save_cache:
        paths:
        - ./node_modules
        key: *cache-key

  unit-test:
    executor: node
    steps:
    - checkout-and-restore-cache
    - run:
        name: Run tests
        command: yarn test

  lint:
    executor: node
    steps:
    - checkout-and-restore-cache
    - run:
        name: Run eslint
        command: yarn lint

  build:
    executor: node
    steps:
    - checkout-and-restore-cache
    - run:
        name: Build sources
        command: yarn build
    - persist_to_workspace:
        root: ~/repo
        paths:
        - lib

  dry-release:
    executor: node
    steps:
    - checkout-and-restore-cache
    - attach_workspace:
        at: ~/repo
    - set-git-write-access
    - run:
        name: Create release
        command: yarn semantic-release --dry-run --branch ${CIRCLE_BRANCH}

  release:
    executor: node
    steps:
    - checkout-and-restore-cache
    - attach_workspace:
        at: ~/repo
    - set-git-write-access
    - run:
        name: Create release
        command: yarn semantic-release


# ------------------------------
# Workflow
# ------------------------------

workflows:
  main-workflow:
    jobs:
    - dependencies
    - unit-test:
        requires:
        - dependencies
    - lint:
        requires:
        - dependencies
    - build:
        requires:
        - dependencies
    - dry-release:
        context: NpmReleasePublish
        requires:
        - unit-test
        - lint
        - build
        filters:
          branches:
            ignore: master
    - hold-release:
        type: approval
        filters:
          branches:
            only: master
    - release:
        context: NpmReleasePublish
        requires:
        - unit-test
        - lint
        - build
        - hold-release
        filters:
          branches:
            only: master
